<?php

return array(
    'urlFormat' => 'path',
    'showScriptName' => false,
    'urlSuffix' => '/',
    'useStrictParsing' => true,
    'rules' => array(
        /*************************
         *      CONTROLLERS      *
         *************************/

        /**-------------------------------------------------------------------------- API --------------------------------------------------*/
        '<_v>/api/clubs' => 'api/<_v>/api/clubs',
        '<_v>/api/clubs/<id:\d+>' => 'api/<_v>/api/clubs',
        '<_v>/api/users' => 'api/<_v>/api/users',
        '<_v>/api/users/<id:\d+>' => 'api/<_v>/api/users',
        '<_v>/api/comments' => 'api/<_v>/api/comments',
        '<_v>/api/comments/<id:\d+>' => 'api/<_v>/api/comments',
        '<_v>/api/posts' => 'api/<_v>/api/posts',
        '<_v>/api/posts/<id:\d+>' => 'api/<_v>/api/posts',
        '<_v>/api/posts/<action:(my)>' => 'api/<_v>/api/posts',
        //'<_v>/api/post-content' => 'api/<_v>api/postContent',
        //'<_v>/api/post-label' => 'api/<_v>/api/postLabel',
        //'<_v>/api/post-tag' => 'api/<_v>/api/postTag',
        '<_v>/api/onair' => 'api/<_v>/api/onair',
        '<_v>/api/sections' => 'api/<_v>/api/sections',
        '<_v>/api/sections/<id:\d+>' => 'api/<_v>/api/sections',
        '<_v>/api/forums' => 'api/<_v>/api/forums',
        '<_v>/api/forums/<id:\d+>' => 'api/<_v>/api/forums',
        '<_v>/api/rubrics' => 'api/<_v>/api/rubrics',
        '<_v>/api/rubrics/<id:\d+>' => 'api/<_v>/api/rubrics',
        '<_v>/api/login' => 'api/<_v>/api/login',
        //'<_v>/api/post-comments' => 'api/<_v>/api/postComments',
        '<_v>/api/photo' => 'api/<_v>/api/photo',
        '<_v>/api/relogin' => 'api/<_v>/api/relogin',
        '<_v>/api/logout' => 'api/<_v>/api/logout',
        '<_v>/api/check-token' => 'api/<_v>/api/checkToken',
        '<_v>/api/ideas' => 'api/<_v>/api/ideas',
        '<_v>/api/ideas/<id:\d+>' => 'api/<_v>/api/ideas',
        '<_v>/api/questions' => 'api/<_v>/api/questions',
        '<_v>/api/questions/<id:\d+>' => 'api/<_v>/api/questions',
        '<_v>/api/answers' => 'api/<_v>/api/answers',
        '<_v>/api/answers/<action:(additional|next)>' => 'api/<_v>/api/answers',
        '<_v>/api/answers/<id:\d+>' => 'api/<_v>/api/answers',
        '<_v>/api/qa-categories' => 'api/<_v>/api/qaCategories',
        '<_v>/api/qa-categories/<id:\d+>' => 'api/<_v>/api/qaCategories',
        '<_v>/api/register' => 'api/<_v>/api/register',
        '<_v>/api/social-register' => 'api/<_v>/api/social-register',
        '<_v>/api/device-register' => 'api/<_v>/api/device-register',
        '<_v>/api/device-unregister' => 'api/<_v>/api/device-unregister',
        '<_v>/api/cache' => 'api/<_v>/api/cache',
        '<_v>/api/logs' => 'api/<_v>/api/logs',
        '<_v>/api/signals' => 'api/<_v>/api/signals',
        '<_v>/api/messages' => 'api/<_v>/api/messages',
        '<_v>/api/dialogs' => 'api/<_v>/api/dialogs',
        '<_v>/api/blacklist' => 'api/<_v>/api/blacklist',
        '<_v>/api/contacts' => 'api/<_v>/api/contacts',
        '<_v>/api/applications' => 'api/<_v>/api/applications',
        '<_v>/api/applications/<action:(default)>' => 'api/<_v>/api/applications',
        '<_v>/api/photo-post' => 'api/<_v>/api/photo-post',
        '<_v>/api/init' => 'api/<_v>/api/init',
        '<_v>/api/answer/vote' => 'api/<_v>/api/vote',
        '<_v>/api/users/rating' => 'api/<_v>/api/rating',
        '<_v>/api/contest' => 'api/<_v>/api/contest',
        '<_v>/api/quests' => 'api/<_v>/api/quests',
        '<_v>/api/subscribe' => 'api/<_v>/api/subscribe',
        '<_v>/api/(favourites|favorites)' => 'api/<_v>/api/favourites',
        '<_v>/api/(childs|children)' => 'api/<_v>/api/childs',
        '<_v>/api/users/<action:(profile)>' => 'api/<_v>/api/users',
        '<_v>/api/questions/<action:(search|next)>' => 'api/<_v>/api/questions',
        '<_v>/api/users/<action:(social)>' => 'api/<_v>/api/users',
        '<_v>/api/clinics' => 'api/<_v>/api/clinics',
        '<_v>/api/specialists' => 'api/<_v>/api/specialists',
        '<_v>/api/specialists/<id:\d+>' => 'api/<_v>/api/specialists',
        '<_v>/api/specialists/<action:(categories|experience|terms|check-terms|specialization|education|courses|career)>' => 'api/<_v>/api/specialists',
        '<_v>/api/specialists/specializations' => 'api/<_v>/api/specializations',
        '<_v>/api/specialists/register/social' => 'api/<_v>/api/specialists-register',
        '<_v>/api/geo/<action:(countries|cities)>' => 'api/<_v>/api/geo',
        /**-------------------------------------------------------------------------- API END ----------------------------------------------*/

        /* API */
        'api/specialists/<_a>' => 'specialists/api/<_a>',
        'api/pediatrician/<_a>' => 'specialists/pediatrician/api/<_a>',
        'api/nextPost/<_a>' => 'posts/nextPost/api/<_a>',
        'api/photoAds/<_a>' => 'posts/photoAds/api/<_a>',
        'api/myGiraffe/<_a>' => 'posts/myGiraffe/api/<_a>',
        'api/comments/<_a>' => 'comments/api/<_a>',
        'api/commentatorsContest/<_a>' => 'comments/contest/api/<_a>',
        'api/status/<_a>' => 'som/status/api/<_a>',
        'api/photopost/<_a>' => 'som/photopost/api/<_a>',
        'api/activity/<_a>' => 'som/activity/api/<_a>',
        'api/community/<_a:(getUserSubscriptions|setUserSubscriptions)>' => 'community/api/<_a>',
        'api/community/<_a>' => 'som/community/api/<_a>',
        'api/qa/<_a>' => 'som/qa/api/<_a>',
        'api/<_m>/<_c>/<_a>' => '<_m>/<_c>Api/<_a>',
        'api/<_m>/<_a>' => '<_m>/api/<_a>',

        /* IFRAME */
        'questions/question<id:\d+>' => 'iframe/default/view',
        '/<tab:(all|new-q|unanswered)>/<tagId:\d+>' => 'iframe/default/pediatrician',
        '/<tab:(all|new-q|unanswered)>' => 'iframe/default/pediatrician',
        '/' => array('iframe/default/pediatrician', 'defaultParams' => array('tab' => 'new-q')),
        'add' => 'iframe/default/pediatricianAddForm',
        'pediatricians' => 'iframe/default/pediatricianList',
        'edit/<questionId:\d+>' => 'iframe/default/pediatricianEditForm',
        'questions/<categoryId:\d+>/page<page:\d+>' => array('iframe/default/index', 'defaultParams' => array('tab' => 'new')),
        'questions/<categoryId:\d+>/<tagId:\d+>' => array('iframe/default/index', 'defaultParams' => array('tab' => 'new')),
        'questions/<categoryId:\d+>' => array('iframe/default/index', 'defaultParams' => array('tab' => 'new')),
        ['class' => 'site\frontend\modules\iframe\modules\specialists\components\SpecialistsUrlRule'],
        'user/<userId:\d+>/info' => 'iframe/specialists/profile/info',
        'specialists/editProfile' => 'iframe/specialists/default/index',
        'user/<userId:\d+>' => 'iframe/userProfile/default/index',
        'user/<userId:\d+>/family/photo<photoId:\d+>' => 'iframe/photo/singlePhoto/family',
        'user/<userId:\d+>/family' => 'iframe/family/default/index',
        'user/<userId:\d+>/family/edit' => 'iframe/family/default/fill',
        'notifications' => 'iframe/notifications/default/index',
        'notifications/<_a>' => 'iframe/notifications/default/<_a>',
        'questions/my/answers/<categoryId:\d+>/page<page:\d+>' => 'iframe/my/answers',
        'questions/my/answers/<categoryId:\d+>' => 'iframe/my/answers',
        'questions/my/answers/page<page:\d+>' => 'iframe/my/answers',
        'questions/my/answers' => 'iframe/my/answers',
        'questions/my/<categoryId:\d+>/page<page:\d+>' => 'iframe/my/questions',
        'questions/my/<categoryId:\d+>' => 'iframe/my/questions',
        'questions/my/page<page:\d+>' => 'iframe/my/questions',
        'questions/my' => 'iframe/my/questions',
        'search/page<page:\d+>' => 'iframe/default/pediatricianSearch',
        'search' => 'iframe/default/pediatricianSearch',
        'logout' => 'iframe/default/logout',
        'iframe/api/<_a>' => 'iframe/api/<_a>',
        'iframe/admin' => 'iframe/admin/default/index',
        'iframe/admin/<_a>' => 'iframe/admin/default/<_a>',
            'online-chat' => 'iframe/landing/index',
            
        'signup/<_c>/<_a>' => 'signup/<_c>/<_a>',
        'reg/test' => 'signup/test/reg',
        'signup/default/captcha' => 'signup/default/captcha',
    ),
);
