<style type="text/css">
    #wrapper{
        width: 100% !important;
    }
</style>
<h1>Статистика сайта за 2011 го</h1>
<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'keywords-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        'name',
        array(
            'name'=>'all',
            'value'=>'$data->GetSummStats()',
        ),
        array(
            'name'=>'avarage',
            'value'=>'$data->GetAverageStats()',
        ),
        array(
            'name'=>'m12',
            'value'=>'$data->GetMonthStats(12)',
        ),
        array(
            'name'=>'m11',
            'value'=>'$data->GetMonthStats(11)',
        ),
        array(
            'name'=>'m10',
            'value'=>'$data->GetMonthStats(10)',
        ),
        array(
            'name'=>'m9',
            'value'=>'$data->GetMonthStats(9)',
        ),
        array(
            'name'=>'m8',
            'value'=>'$data->GetMonthStats(8)',
        ),
        array(
            'name'=>'m7',
            'value'=>'$data->GetMonthStats(7)',
        ),
        array(
            'name'=>'m6',
            'value'=>'$data->GetMonthStats(6)',
        ),
        array(
            'name'=>'m5',
            'value'=>'$data->GetMonthStats(5)',
        ),
        array(
            'name'=>'m4',
            'value'=>'$data->GetMonthStats(4)',
        ),
        array(
            'name'=>'m3',
            'value'=>'$data->GetMonthStats(3)',
        ),
        array(
            'name'=>'m2',
            'value'=>'$data->GetMonthStats(2)',
        ),
        array(
            'name'=>'m1',
            'value'=>'$data->GetMonthStats(1)',
        ),
    ),
)); ?>