<?php
/**
 * User: alexk984
 * Date: 10.03.12
 *
 */
class VUsersCommand extends CConsoleCommand
{
    public $virtual_users = 'gorbunova.kn@gmail.com
moyarabota19_hg@mail.ru
moyarabota18_hg@mail.ru
moyarabota17_hg@mail.ru
moyarabota16_hg@mail.ru
moyarabota15_hg@mail.ru
moyarabota14_hg@mail.ru
moyarabota13_hg@mail.ru
moyarabota12_hg@mail.ru
moyarabota11_hg@mail.ru
moyarabota10_hg@mail.ru
moyarabota9_hg@mail.ru
moyarabota8_hg@mail.ru
moyarabota7_hg@mail.ru
moyarabota6_hg@mail.ru
moyarabota1_hg@mail.ru
moyarabota2_hg@mail.ru
moyarabota3_hg@mail.ru
moyarabota4_hg@mail.ru
moyarabota5_hg@mail.ru
mamonenok09@list.ru
vartanov_zhora@list.ru
glupishka1@list.ru
glupishka2@list.ru
glupishka3@list.ru
glupishka4@list.ru
glupishka5@list.ru
glupishka8@list.ru
glupishka7@list.ru
glupishka6@list.ru
ms.batkovna@list.ru
kirill.m.2011@list.ru
glupishka9@list.ru
glupishka10@list.ru
glupishka12@list.ru
glupishka13@list.ru
glupishka18@list.ru
glupishka5@gmail.com
glupishka14@list.ru
glupishka16@list.ru
glupishka17@list.ru
mpolincka@yandex.ru
rabotaem.jiraf8@mail.ru
slavutaberdyansk@rambler.ru
knopka122@mail.ru
kaktuzcom@mail.ru
lacetticom@mail.ru
alexmorfkrukov@mail.ru
kryukova1989@inbox.ru
kryukova_00_00@mail.ru
ms.knopka123@mail.ru
knopka1966@bk.ru
ilona.kryuk@bk.ru
rabotaem.jiraf@mail.ru
rabotaem.jiraf2@mail.ru
rabotaem.jiraf3@mail.ru
rabotaem.jiraf4@mail.ru
rabotaem.jiraf5@mail.ru
rabotaem.jiraf6@mail.ru
rabotaem.jiraf7@mail.ru
zhiraf-mama@mail.ru
uraichanka@yandex.ru
teen.aprel@yandex.ru
pozitiv_meridian@mail.ru
zloyzayez@gmail.com
babka.makapka@gmail.com
tatkapechkina@gmail.com
mdebra@mail.ru
zhiraf-dva@mail.ru
zhiraf-tri@mail.ru
zhiraf-mashama@mail.ru
zhiraf4@mail.ru
zhiraf.tolkorodila@mail.ru
40-let@inbox.ru
zhiraf-papa@mail.ru
al.vavilova2012@yandex.ru
zhiraf-01@mail.ru
zhiraf-02@mail.ru
zhiraf-03@mail.ru
aprel.00@inbox.ru
maximata@yandex.ru
ave-mark@yandex.ru
vlad-mirom@mail.ru
raz2liz@yandex.ru
zawada@yandex.ru
argentiras@yandex.ru
silimam@yandex.ru
figanulya@yandex.ru
artylog@yandex.ru
my.colour.world.1@gmail.com
mamma_mi@mail.ru
al.vavilova@yandex.ru
tazver76@mail.ru
krudmila@mail.ru
AlexST55@mail.ru
dagdja-3@yandex.ru
fieryflash@mail.ru
volokuviriy@mail.ru
limovaelena@mail.ru
dagdja@gmail.com
rabochie2@mail.ru
rabochie3@mail.ru
rabochie14@mail.ru
rabochie5@mail.ru
rabochie6@mail.ru
rabochie7@mail.ru
rabochie8@mail.ru
rabochie9@mail.ru
rabochie10@mail.ru
rabochie11@mail.ru
rabochie12@mail.ru
kozjavka22@mail.ru
kozjavka33@mail.ru
kozjavka55@mail.ru
kozjavka4@mail.ru
kozjavka12@mail.ru
kozjavka70@mail.ru
kozjavka80@mail.ru
kozjavka89@mail.ru
kozjavka911@mail.ru
kozjavka9@mail.ru
kozjavka66@mail.ru
kozjavka1@mail.ru
ingigerda03@yandex.ru
ingigerda83@mail.ru
ingigerd83@gmail.ru
ingigerd83@inbox.ru
ingigerdda03@yandex.ru
ingigerd83@rambler.ru
ingigerda83@inbox.ru
profes3@mail.ru
profes5@mail.ru
profes6@mail.ru
profes8@mail.ru
profes9@mail.ru
profes4@mail.ru
profes11@mail.ru
profes13@mail.ru
nptiza@mail.ru
n1ptiza@mail.ru
n2ptiza@mail.ru
n4ptiza@mail.ru
n5ptiza@mail.ru
n6ptiza@mail.ru
n7ptiza@mail.ru
n8ptiza@mail.ru
n9ptiza@mail.ru
miss.maria-ivanova2013@yandex.ru
iv.marjin@yandex.ru
babagirafa@mail.ru
ogurcov.e@bk.ru
mihef.12@mail.ru
katly1@mail.ru
zhirafa1@mail.ru
surikat_1@mail.ru
surikat_2@mail.ru
surikat-3@mail.ru
surikat-4@mail.ru
surikat-5@mail.ru
surikat_6@mail.ru
surikat_7@mail.ru
surikat_9@mail.ru
olga546@ukr.net
anna544@ukr.net
yana636@ukr.net
valya546@ukr.net
MarsiYanka@list.ru
irina.kondratova@rambler.ru
grigoreva.tatjana@rambler.ru
tamara.gudz@rambler.ru
evgenija.siryh@rambler.ru
julja555@rambler.ru
elya12@rambler.ru
mari6@rambler.ru
inna6555@rambler.ru
jytu66@ukr.net
mary8e@ukr.net
Jane90@ukr.net
maryska54@ukr.net
kdhju5@rambler.ru
belijyaroslava@rambler.ru
bulantanya@rambler.ru
hetrusyana@rambler.ru
rezniksofiya@rambler.ru
kubarsveta@rambler.ru
kapelveronika@rambler.ru
kazimnina@rambler.ru
luhanina.an@yandex.ru
novakovsky.denis@yandex.ru
mariya.markova05@yandex.ru
darya.avetisova@yandex.ru
aleksandr.rodin2013@yandex.ru
miroslav.besedin@yandex.ru
pastuhow.igor2012@yandex.ru
zhdanovtosha@yandex.ru
yurij.hmelnitskij@yandex.ru
valchuk.denis@yandex.ru
stanislav.ejunov@yandex.ru
rudnik.katya@yandex.ru
alyona.ivano2013@yandex.ru
sheptuha.svetlana@yandex.ru
alla.arlinskaya@yandex.ru
bogdan.korol2012@yandex.ru
shishak.darya@yandex.ru
i.pashkovskaya@yandex.ru
jdanowkirill@yandex.ru
konstantin.istratoff@yandex.ru
xenia.constantinowa@yandex.ru
misha.cotlyar@yandex.ru
stepan.manshilin@yandex.ru
belyakowa.dzhulia@yandex.ru
zaikina.iana@yandex.ru
happy-giraffe@ukr.net
happy-giraffe1@ukr.net
happy-giraffe2@ukr.net
happy-giraffe3@ukr.net
happy-giraffe4@ukr.net
happy-giraffe5@ukr.net
happy-giraffe@yandex.ru
happy-giraffe1@yandex.ru
happy-giraffe2@yandex.ru
happy-giraffe3@yandex.ru
happy-giraffe1@rambler.ru
happy-giraffe2@rambler.ru
happy-giraffe3@rambler.ru
happy-giraffe4@rambler.ru
happy-giraffe@mail.ru
happy-giraffe6@ukr.net
happy-giraffe7@ukr.net
happy-giraffe8@ukr.net
happy-giraffe9@ukr.net
happy-giraffe10@ukr.net
Mosina79@bk.ru
n.gubenko@bk.ru
olya.kovalenko.76@bk.ru
zhenya_popova_87@mail.ru
balashova_l@list.ru
orlova-liliya@list.ru
malyuk81@list.ru
gladkih.inna@bk.ru
kiss-anna@bk.ru
petrenko.lesya@bk.ru
ira.kotova.85@bk.ru
ler.mai@yandex.ru
skiba.ira2012@yandex.ru
mart.olia@yandex.ru
sw.liza@yandex.ru
alexsashka64@gmail.com
lina.linaivanova2013@yandex.ru
mil.al2013@yandex.ru
mol.tak@yandex.ru
totak2013@yandex.ru
big.slon2012@yandex.ru
kwit.ka@yandex.ru
busiki.blk@yandex.ru
ligh2013@yandex.ru
anna.jur2012@yandex.ru
orl.marina2013@yandex.ru
happy-giraffe15@ukr.net
happy-giraffe16@ukr.net
happy-giraffe17@ukr.net
happy-giraffe18@ukr.net
happy-giraffe19@ukr.net
happy-giraffe20@ukr.net
happy-giraffe21@ukr.net
happy-giraffe22@ukr.net
happy-giraffe23@ukr.net
happy-giraffe24@ukr.net
happy-giraffe25@mail.ru
happy-giraffe26@mail.ru
happy-giraffe27@mail.ru
happy-giraffe28@mail.ru
happy-giraffe29@bk.ru
happy-giraffe30@mail.ru
happy-giraffe31@mail.ru
happy-giraffe32@bk.ru
happy-giraffe33@bk.ru
happy-giraffe34@bk.ru
happy-giraffe35@bk.ru
happy-giraffe36@yandex.ru
';

    public $moderators = 'mara258@yandex.ru
krasotka_Vikky@mail.ru
yasonechko@mail.ru
rabochie1@mail.ru
krikri25@mail.ru
ingigerd@rambler.ru
profes2@mail.ru
n3ptiza@mail.ru
viktoriD-M@mail.ru
surikat_8@mail.ru';

    public function actionIndex()
    {
        $this->setRole($this->virtual_users, 'virtual user');
        $this->setRole($this->moderators, 'moderator');
    }

    public function setRole($users, $role)
    {
        $list = explode("\n", $users);
        foreach ($list as $userMail) {
            $userMail = trim($userMail);
            $user = User::model()->findByAttributes(array('email' => $userMail));
            //check if user exist
            if ($user !== null){
                //check if user already has role
                $exist_right = Yii::app()->db->createCommand()
                    ->select('COUNT(*)')
                    ->from('auth__assignments')
                    ->where('userid = :userid AND itemname = "'.$role.'"', array(':userid' => $user->id))
                    ->queryScalar();
                if ($exist_right == 0){
                    $success = Yii::app()->db->createCommand()
                        ->insert('auth__assignments', array('userid'=>$user->id, 'itemname'=>$role, 'data'=>'N;'));
                    if (!$success)
                        echo $userMail." insert error \r\n";
                }
            }else{
                echo $userMail."\r\n";
            }
        }
    }
}
